### ISSUE TITLE
Build EPERM Error

### ISSUE THREAD

**Issue by Lypris** [executablebooks/mystmd#1018]
## Description

Hello, when I want to build a jupyterlab `ipynb` file into a `pdf`, I have the following issue:
`EPERM: operation not permitted, scandir 'AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5`

I have tried this with Anaconda Navigator, Jupyterlab 4.0.11, npm 10.5.0 and the lastest version of **MyST** and following tests: 
- in "normal" mode
- anaconda executed as admin
- with all admin permissions enabled on the following directories:
    -      C:\ProgramData\anaconda3
    -      C:\Users\myname\AppData\Local\Microsoft\Windows\INetCache\Low

How can I fix this?

**Comment by rowanc1** [comment]
Can you let us know the command in mystmd that you are using, the mystmd version and the output of putting a debug flag, `-d`, at the end of the mystmd command to see where it gets stuck?

**Comment by Lypris** [comment]
Of course, here are all the infos:
Myst CLI Versions:
 - node                         20.9.0     Required: >= 16.0.0
 - npm                          10.5.0     Required: >=7
 - myst                         1.1.47
 
`myst build TD1.ipynb --pdf -d`

_The result:_
Error: EPERM: operation not permitted, lstat 'C:\Users\myname\AppData\Local\ElevatedDiagnostics'
    at Object.lstatSync (node:fs:1654:3)
    at isDirectory (C:\Users\myname\.conda\envs\jupyter\Lib\site-packages\mystmd_py\myst.cjs:201606:33)
    at C:\Users\myname\.conda\envs\jupyter\Lib\site-packages\mystmd_py\myst.cjs:294568:45
    at Array.filter (<anonymous>)
    at projectPagesFromPath (C:\Users\myname\.conda\envs\jupyter\Lib\site-packages\mystmd_py\myst.cjs:294568:28)
    at C:\Users\myname\.conda\envs\jupyter\Lib\site-packages\mystmd_py\myst.cjs:294570:19
    at Array.map (<anonymous>)
    at projectPagesFromPath (C:\Users\myname\.conda\envs\jupyter\Lib\site-packages\mystmd_py\myst.cjs:294568:83)
    at C:\Users\myname\.conda\envs\jupyter\Lib\site-packages\mystmd_py\myst.cjs:294570:19
    at Array.map (<anonymous>)


EPERM: operation not permitted, lstat 'AppData\Local\ElevatedDiagnostics'

**Comment by rowanc1** [comment]
I am not quite sure what is going on either here. Sorry for the delay in getting back to you.

Have you run `myst init` in the folder (or do you have a `myst.yml` in that folder)? It is possible that there is a bug that is looking recursively upwards for a `myst.yml` and it gets into trouble in a higher-level directory. But it doesn't look like it from the logs...

Let me know if that fixes the problem, regardless!

Another thing that you could try is installing through npm rather than conda? Depending on how you have installed node/npm, it is possible that that is in a folder that is not under the same permissions challenges.

Thanks for your help in tracking this down.
