### ISSUE TITLE
`myst build` ignores `toc` from `myst.yml`

### ISSUE THREAD

**Issue by roaldarbol** [executablebooks/mystmd#1175]
## Description
When attempting to build a PDF with a typst template, and having the ToC file specified under `exports` within `myst.yml`, it throws an error. Basically, it says that it is ignoring the key `toc` although it should be a valid field (https://mystmd.org/guide/documents-exports). Best way to reproduce is from https://github.com/roaldarbol/thesis-template and then building with debug on:
```sh
myst build --typst -d
```
produces (amongst other errors which I suspect are user errors):
```sh
'options' extra key ignored: toc (at /Users/roaldarbol/Filen/Projects/thesis-template/myst.yml)
```

Curiously, it also builds all pages separately first which I think is unintended, but may be due to the problem.

<details>

```sh
❯ myst build --typst -d
Loaded site config from /Users/roaldarbol/Filen/Projects/thesis-template/myst.yml
Loaded project config from /Users/roaldarbol/Filen/Projects/thesis-template/myst.yml
(node:88463) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


Myst CLI Versions:
 - node                         22.0.0     Required: >= 18.0.0      
 - npm                          10.7.0     Required: >=8.6.0        
 - myst                          1.2.0     


Basic validation of TOC passed
Basic validation of TOC passed
🔍 /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-typst/main.bib exists, but the file is not referenced in /Users/roaldarbol/Filen/Projects/thesis-template/myst.yml#bibliography
Exporting formats: "typst"
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/README.md in 42 ms.
Basic validation of TOC passed
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/00-Front-Page.md in 3.01 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/01-Declaration.md in 3.32 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/02-Abstract.md in 2.23 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/03-Preface.md in 3.67 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/04-Acknowledgements.md in 2.56 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/05-Dedication.md in 2.16 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/06-Glossary.md in 6.51 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/01-Chapters/01-Introduction.md in 5.84 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/01-Chapters/02-Chapter.md in 3.99 ms.
📬 Performing exports:
   myst.yml -> _build/exports/myst_typst/myst.pdf
Loaded site config from /Users/roaldarbol/Filen/Projects/thesis-template/myst.yml
Loaded project config from /Users/roaldarbol/Filen/Projects/thesis-template/myst.yml
Basic validation of TOC passed
Basic validation of TOC passed
🔍 /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-typst/main.bib exists, but the file is not referenced in /Users/roaldarbol/Filen/Projects/thesis-template/myst.yml#bibliography
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/01-Declaration.md in 2.39 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/02-Abstract.md in 2.69 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/03-Preface.md in 1.77 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/04-Acknowledgements.md in 3.12 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/05-Dedication.md in 2.45 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/06-Glossary.md in 3.51 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/01-Chapters/01-Introduction.md in 2.54 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/01-Chapters/02-Chapter.md in 3.35 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/README.md in 5.01 ms.
loadFile: loaded /Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/00-Front-Page.md in 4.21 ms.
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/01-Declaration.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/02-Abstract.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/03-Preface.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/04-Acknowledgements.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/05-Dedication.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/06-Glossary.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/01-Chapters/01-Introduction.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/01-Chapters/02-Chapter.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/README.md"
Processing "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/00-Front-Page.md"
📖 Built examples/example-myst/00-Front-Matter/01-Declaration.md in 50 ms.
📖 Built examples/example-myst/00-Front-Matter/02-Abstract.md in 49 ms.
📖 Built examples/example-myst/00-Front-Matter/03-Preface.md in 49 ms.
📖 Built examples/example-myst/00-Front-Matter/04-Acknowledgements.md in 48 ms.
📖 Built examples/example-myst/00-Front-Matter/05-Dedication.md in 48 ms.
📖 Built examples/example-myst/00-Front-Matter/06-Glossary.md in 48 ms.
📖 Built README.md in 38 ms.
📖 Built examples/example-myst/00-Front-Matter/00-Front-Page.md in 37 ms.
📖 Built examples/example-myst/01-Chapters/01-Introduction.md in 67 ms.
📖 Built examples/example-myst/01-Chapters/02-Chapter.md in 65 ms.
Transformed mdast cross references and links for "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/01-Declaration.md" in 3.04 ms
Transformed mdast cross references and links for "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/02-Abstract.md" in 2.45 ms
Transformed mdast cross references and links for "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/03-Preface.md" in 2.41 ms
Transformed mdast cross references and links for "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/04-Acknowledgements.md" in 2.38 ms
Transformed mdast cross references and links for "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/05-Dedication.md" in 2.36 ms
Transformed mdast cross references and links for "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/00-Front-Matter/06-Glossary.md" in 2.55 ms
Transformed mdast cross references and links for "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/01-Chapters/01-Introduction.md" in 2.59 ms
Transformed mdast cross references and links for "/Users/roaldarbol/Filen/Projects/thesis-template/examples/example-myst/01-Chapters/02-Chapter.md" in 3.03 ms
📚 Built 10 pages for export (including 2 dependencies) from /Users/roaldarbol/Filen/Projects/thesis-template in 111 ms.
Template found: /Users/roaldarbol/Filen/Projects/thesis-template
⛔️ Unhandled Typst conversion for node of "glossary"
To suppress this message, add rule: "myst-to-typst" to "error_rules" in your project config
📑 Exported typst in 39 ms, copying to _build/temp/myst2y4DzN/myst.typ
'options' extra key ignored: toc (at /Users/roaldarbol/Filen/Projects/thesis-template/myst.yml)


Template render error: (/Users/roaldarbol/Filen/Projects/thesis-template/typst-thesis.typ) [Line 7, Column 25]
  unknown block tag: it
    at Object._prettifyError (/Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:104315:15)
    at Template2.render3 [as render] (/Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:109409:25)
    at /Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:109280:31
    at createTemplate2 (/Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:109240:13)
    at handle6 (/Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:109251:15)
    at /Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:109260:13
    at next (/Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:104524:11)
    at Object.asyncIter (/Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:104529:7)
    at Environment2.getTemplate (/Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:109245:13)
    at Environment2.render3 [as render] (/Users/roaldarbol/Filen/Projects/thesis-template/.pixi/envs/default/lib/python3.12/site-packages/mystmd_py/myst.cjs:109274:14)


Template render error: (/Users/roaldarbol/Filen/Projects/thesis-template/typst-thesis.typ) [Line 7, Column 25]
  unknown block tag: it
```

</details>

**Comment by roaldarbol** [comment]
Related, when specifying file names for Multi-Article exports, they need to have the `.md` suffix, whereas the normal `_toc.yml` doesn't require it. Not really an issue, but an inconsistency. @agoose77 maybe this will be more streamlined with the new ToC format?
